name: Register Shared Workflows
description: Action to register shared workflows
author: bubkoo <bubkoo.wy@gmail.com>
branding:
  icon: check-circle
  color: green
inputs:
  id:
    description: The ID of run (provided by GitHub app via `github.event.client_payload.id`)
    required: true
  run_id:
    description: The ID of workflow run (provided via GitHub syntax `github.run_id`)
    required: true
  name:
    description: The name of check (Use `github.workflow` to use the name of the workflow)
    required: true
  callback:
    description: The callback url for register call (provided by GitHub app via `github.event.client_payload.callback`)
    required: true
  sha:
    description: The sha of original commit (provided by GitHub app via `github.event.client_payload.sha`)
    required: true
  enforce:
    description: Enforce [required status check](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks)
    required: false
    default: false
  enforce_admin:
    description: Enforce [required status check](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks) for admins
    required: false
    default: false
  doc_path:
    description: Link to documentation of this check. This is shown with the status check on the original commit. (eg `.github/workflows/compliance-info.md`)
    required: false
runs:
  using: composite
  steps:
    - run: |
        curl -G \
          "${{ inputs.callback }}" \
          -d id=${{ inputs.id }} \
          -d run_id=${{ inputs.run_id }} \
          -d sha=${{ inputs.sha }} \
          -d enforce=${{ inputs.enforce }} \
          -d enforce_admin=${{ inputs.enforce_admin }} \
          --data-urlencode "name=${{ env.name || github.workflow }}" \
          --data-urlencode "doc_path=${{ inputs.doc_path }}"
      shell: bash
