name: test

on: push

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: bubkoo/bot@master
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: "Central markdown check"
        enforce: true
        doc_path: "./examples/workflow-readme.md"

    - uses: bubkoo/bot/src/rsw@master
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: "Central markdown check"
        enforce: true
        doc_path: "./examples/workflow-readme.md"
